//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleParser.Core
{
    using System; using Svyaznoy.Core.Model;
    using System.Collections.Generic;
    
    public partial class DbRegistratorChanges : IRegistratorChanges
    {
        public System.Guid Id { get; set; }
        public System.Guid ObjectId { get; set; }
        public string EntityName { get; set; }
        public string PropertyName { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public int EntityState { get; set; }
        public System.DateTime CreatedUtcDate { get; set; }
        public Nullable<System.DateTime> UpdatedUtcDate { get; set; }
    }
}
